import type { Config } from 'tailwindcss';
import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

/**
 * Ported verbatim from the original `window.SmartMinTailwindConfig`
 * (assets/js/shared.js) so the Next.js UI is byte-for-byte identical
 * to the static HTML/CSS/JS app.
 */
const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#616363',
        'on-error': '#ffffff',
        'on-primary-container': '#ff8371',
        secondary: '#5d5f5f',
        'on-background': '#1a1c1c',
        tertiary: '#735c00',
        'surface-bright': '#f9f9f9',
        'primary-container': '#800000',
        'on-secondary-fixed-variant': '#454747',
        'tertiary-fixed': '#ffe088',
        error: '#ba1a1a',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        'inverse-surface': '#2f3131',
        'surface-container-high': '#e8e8e8',
        'surface-tint': '#b22b1d',
        'primary-fixed': '#ffdad4',
        'on-tertiary-container': '#4e3d00',
        'surface-container-highest': '#e2e2e2',
        'outline-variant': '#e2bfb9',
        'secondary-container': '#dfe0e0',
        'primary-fixed-dim': '#ffb4a8',
        'on-surface-variant': '#5a413d',
        'tertiary-container': '#cba72f',
        'on-secondary-fixed': '#1a1c1c',
        surface: '#f9f9f9',
        'on-primary-fixed-variant': '#8f0f07',
        'on-primary': '#ffffff',
        'surface-dim': '#dadada',
        'error-container': '#ffdad6',
        background: '#f9f9f9',
        'surface-container': '#eeeeee',
        primary: '#570000',
        'on-tertiary-fixed-variant': '#574500',
        'inverse-on-surface': '#f1f1f1',
        'surface-variant': '#e2e2e2',
        'secondary-fixed-dim': '#c6c6c7',
        'on-error-container': '#93000a',
        'secondary-fixed': '#e2e2e2',
        'inverse-primary': '#ffb4a8',
        'on-tertiary-fixed': '#241a00',
        outline: '#8e706c',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed': '#410000',
        'on-surface': '#1a1c1c',
        'tertiary-fixed-dim': '#e9c349',
        'surface-container-low': '#f3f3f3',
        success: '#2e7d32',
        'success-container': 'rgba(46,125,50,0.12)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        margin: '32px',
        lg: '24px',
        xs: '4px',
        xxl: '64px',
        md: '16px',
        'container-max': '1440px',
        xl: '40px',
        gutter: '24px',
        sm: '8px',
      },
      fontFamily: {
        'body-md': ['Inter'],
        h1: ['Public Sans'],
        h3: ['Public Sans'],
        h2: ['Public Sans'],
        'body-sm': ['Inter'],
        'label-caps': ['Inter'],
        'body-lg': ['Inter'],
        caption: ['Inter'],
        display: ['Public Sans'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        h1: ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        h3: ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        h2: ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        caption: ['12px', { lineHeight: '1.4', fontWeight: '400' }],
        display: ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [forms, containerQueries],
};

export default config;
