// EN <-> Tagalog dictionary translator — faithful TS port of assets/js/translator.js.
// Demo-grade; used as the offline fallback for the (real, Claude-backed)
// translation route in Phase 5. Produces plausible output for meeting vocabulary.

import type { TranscriptSegment } from './types';

const EN_TL: Record<string, string> = {
  'good morning': 'magandang umaga',
  'good afternoon': 'magandang hapon',
  'thank you': 'salamat',
  'thank you all': 'salamat sa inyong lahat',
  colleagues: 'mga kasamahan',
  meeting: 'pulong',
  faculty: 'guro',
  'faculty senate': 'kapulungan ng guro',
  'monthly sync': 'buwanang pagpupulong',
  curriculum: 'kurikulum',
  budget: 'badyet',
  infrastructure: 'imprastraktura',
  committee: 'komite',
  priority: 'prayoridad',
  replacement: 'pagpapalit',
  networking: 'networking',
  equipment: 'kagamitan',
  department: 'departamento',
  'meeting was called to order': 'pormal na binuksan ang pulong',
  'i agree': 'sumasang-ayon ako',
  'i second the motion': 'sinusuportahan ko ang mosyon',
  'approved without corrections': 'inaprubahan nang walang pagbabago',
  'next week': 'sa susunod na linggo',
  'by next week': 'sa susunod na linggo',
  'next month': 'sa susunod na buwan',
  deadline: 'huling araw',
  submit: 'isumite',
  'submit the': 'isumite ang',
  report: 'ulat',
  finalize: 'tapusin',
  review: 'suriin',
  discuss: 'talakayin',
  discussed: 'tinalakay',
  'we need to': 'kailangan nating',
  'we will': 'tayo ay',
  'i will': 'ako ay',
  will: 'ay magsasagawa ng',
  shall: 'ay magsasagawa ng',
  must: 'dapat',
  should: 'kailangang',
  request: 'kahilingan',
  approve: 'aprubahan',
  approved: 'inaprubahan',
  pending: 'nakabinbin',
  'in progress': 'nagaganap',
  done: 'tapos na',
  university: 'unibersidad',
  college: 'kolehiyo',
  office: 'tanggapan',
  president: 'pangulo',
  dean: 'dekano',
  secretary: 'kalihim',
  staff: 'kawani',
  student: 'mag-aaral',
  students: 'mga mag-aaral',
  workshop: 'palihan',
  training: 'pagsasanay',
  evaluation: 'pagsusuri',
  accreditation: 'akreditasyon',
  syllabus: 'silabus',
  syllabi: 'mga silabus',
  instructor: 'tagapagturo',
  instructors: 'mga tagapagturo',
  professor: 'propesor',
  document: 'dokumento',
  documents: 'mga dokumento',
  schedule: 'iskedyul',
  conflict: 'salungatan',
  'meeting is adjourned': 'tapos na ang pulong',
  adjourned: 'tapos na',
  present: 'iharap',
  presented: 'iniharap',
  agenda: 'adyenda',
  good: 'mabuti',
  today: 'ngayon',
  tomorrow: 'bukas',
  yesterday: 'kahapon',
  morning: 'umaga',
  afternoon: 'hapon',
  evening: 'gabi',
  with: 'kasama',
  without: 'walang',
  and: 'at',
  or: 'o',
  the: 'ang',
  a: 'isang',
  is: 'ay',
  are: 'ay',
  for: 'para sa',
  to: 'sa',
  of: 'ng',
  in: 'sa',
  on: 'sa',
  at: 'sa',
  this: 'ito',
  that: 'iyan',
  these: 'ang mga ito',
  those: 'ang mga iyon',
  please: 'paki',
  coordinate: 'i-koordinasyon',
  finance: 'pinansya',
  'academic affairs': 'mga gawaing akademiko',
  'vice president': 'pangalawang pangulo',
  board: 'lupon',
  quorum: 'kumporme',
  motion: 'mosyon',
  minutes: 'katitikan',
  previous: 'nakaraan',
  team: 'koponan',
  project: 'proyekto',
  task: 'gawain',
  tasks: 'mga gawain',
  'action items': 'mga gawaing aksyon',
};

const TL_EN: Record<string, string> = {
  'magandang umaga': 'good morning',
  'magandang hapon': 'good afternoon',
  salamat: 'thank you',
  'salamat sa inyong lahat': 'thank you all',
  'mga kasamahan': 'colleagues',
  pulong: 'meeting',
  pagpupulong: 'meeting',
  guro: 'faculty',
  kurikulum: 'curriculum',
  badyet: 'budget',
  departamento: 'department',
  kolehiyo: 'college',
  unibersidad: 'university',
  pangulo: 'president',
  dekano: 'dean',
  kalihim: 'secretary',
  'mag-aaral': 'student',
  'mga mag-aaral': 'students',
  silabus: 'syllabus',
  'mga silabus': 'syllabi',
  iskedyul: 'schedule',
  'huling araw': 'deadline',
  ulat: 'report',
  aprubahan: 'approve',
  inaprubahan: 'approved',
  nakabinbin: 'pending',
  'tapos na': 'done',
  palihan: 'workshop',
  pagsasanay: 'training',
  pagsusuri: 'evaluation',
  akreditasyon: 'accreditation',
  tagapagturo: 'instructor',
  'mga tagapagturo': 'instructors',
  propesor: 'professor',
  dokumento: 'document',
  'mga dokumento': 'documents',
  salungatan: 'conflict',
  kailangan: 'need',
  dapat: 'must',
  kasama: 'with',
  walang: 'without',
  at: 'and',
  o: 'or',
  ang: 'the',
  isang: 'a',
  'para sa': 'for',
  sa: 'to',
  ng: 'of',
  ito: 'this',
  iyan: 'that',
  paki: 'please',
  mosyon: 'motion',
  katitikan: 'minutes',
  lupon: 'board',
  'mga gawain': 'tasks',
  gawain: 'task',
  'mga gawaing aksyon': 'action items',
  proyekto: 'project',
  koponan: 'team',
  pinansya: 'finance',
};

function translateString(text: string, dict: Record<string, string>): string {
  if (!text) return text;
  let result = text;
  const keys = Object.keys(dict).sort((a, b) => b.length - a.length);
  for (const k of keys) {
    const re = new RegExp('\\b' + k.replace(/[-/\\^$*+?.()|[\]{}]/g, '\\$&') + '\\b', 'gi');
    result = result.replace(re, (m) => {
      const tr = dict[k];
      if (m[0] === m[0].toUpperCase()) return tr[0].toUpperCase() + tr.slice(1);
      return tr;
    });
  }
  return result;
}

export type TranslateDirection = 'en-tl' | 'tl-en';

export function translate(text: string, direction: TranslateDirection = 'en-tl'): string {
  return translateString(text, direction === 'tl-en' ? TL_EN : EN_TL);
}

export function translateSegments(segments: TranscriptSegment[], direction: TranslateDirection = 'en-tl'): TranscriptSegment[] {
  return segments.map((s) => ({ ...s, text: translate(s.text, direction) }));
}
